version: "3.9"

services:
  backend:
    build: ./backend
    container_name: progressive-backend
    ports:
      - "5000:5000"
    volumes:
      - C:/Users/BAPS/.aws:/root/.aws
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: progressive-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped